// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNs8HjJlruomJ2YUT315OjB0iKRcKjEkc',
    appId: '1:466313513653:web:2463e55c79eed3755b0cfc',
    messagingSenderId: '466313513653',
    projectId: 'harmony-by-intent',
    authDomain: 'harmony-by-intent.firebaseapp.com',
    storageBucket: 'harmony-by-intent.firebasestorage.app',
    measurementId: 'G-5M4TCRS358',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSn_iS5Yv_hlcyWi9dhm7rKGRy8Zu36yI',
    appId: '1:466313513653:android:2587458124bdf80a5b0cfc',
    messagingSenderId: '466313513653',
    projectId: 'harmony-by-intent',
    storageBucket: 'harmony-by-intent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFBuYcAAx3ohunxtGhEHPSiL0weiHEg5M',
    appId: '1:466313513653:ios:eead42dcce87f08c5b0cfc',
    messagingSenderId: '466313513653',
    projectId: 'harmony-by-intent',
    storageBucket: 'harmony-by-intent.firebasestorage.app',
    iosBundleId: 'com.harmonybyintent.harmonyUserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFBuYcAAx3ohunxtGhEHPSiL0weiHEg5M',
    appId: '1:466313513653:ios:eead42dcce87f08c5b0cfc',
    messagingSenderId: '466313513653',
    projectId: 'harmony-by-intent',
    storageBucket: 'harmony-by-intent.firebasestorage.app',
    iosBundleId: 'com.harmonybyintent.harmonyUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNs8HjJlruomJ2YUT315OjB0iKRcKjEkc',
    appId: '1:466313513653:web:82df626f6b5ae22a5b0cfc',
    messagingSenderId: '466313513653',
    projectId: 'harmony-by-intent',
    authDomain: 'harmony-by-intent.firebaseapp.com',
    storageBucket: 'harmony-by-intent.firebasestorage.app',
    measurementId: 'G-B0E9N4FXKX',
  );
}
